#' Prepare data for PCA.
#'
#' @description
#' Rows (proteins) with too many missing values are removed. If missing values
#' remain (propNA < 0), the remaining missing values need to be imputed, as the
#' PCA cannot deal with incomplete data.
#' Additionally, proteins with almost constant values (and therefor a variance
#' near zero are removed).
#'
#' @param **SummarizedExperiment object** \cr
#' Data in a SummarizedExperiment object, e.g. output SE from [prepareDataSE]
#' function.
#' @param assay **character(1)** \cr
#' The name of the assay in SE containing the protein intensities that should
#' be used for the PCA plot. Default is "intensity_norm", which uses the
#' normalized protein intensities if the SE object was generated by
#' [prepareDataSE].
#' @param imputeMethod **character(1)** \cr
#' The missing value imputation method. Options are "mean" or "median" or
#' "none" (default).
#' @param propNA **numeric(1)** \cr
#' The proportion of allowed missing values for a protein, before it is
#' discarded. It is automatically set to 0 if imputeMethod is "none".
#' @param verbose **logical(1)** \cr
#' If TRUE, messages are printed out.
#'
#' @importFrom checkmate assertFlag assertNumeric assertSubset assertTRUE
#' @importFrom matrixStats rowVars
#' @importFrom SummarizedExperiment assays
#'
#'
#' @return SummarizedExperiment object with the filtered data.
.prepDataForPCA <- function(SE, assay = "intensity_norm",
                            imputeMethod = "none", propNA = 0,
                            verbose = TRUE) {
  checkmate::assertSubset(assay, names(SummarizedExperiment::assays(SE)))
  checkmate::assertSubset(imputeMethod, c("mean", "median", "none"))
  checkmate::assertNumeric(propNA, lower = 0, upper = 1)
  checkmate::assertFlag(verbose)

  # proportion of missing values per protein
  D_all <- SummarizedExperiment::assays(SE)[[assay]]
  mean_NA <- apply(D_all, 1, function(x) mean(is.na(x)))

  ### remove rows with too many missing values
  if (imputeMethod == "none") propNA <- 0
  index_to_keep <- mean_NA <= propNA
  SE <- SE[index_to_keep, ]

  ## impute missing values
  if (imputeMethod != "none") {
    D <- SummarizedExperiment::assays(SE)[[assay]]
    D <- as.data.frame(t(apply(D, 1, function(x) {
      if (anyNA(x)) {
        x[is.na(x)] <- switch(imputeMethod, mean = mean(x, na.rm = TRUE),
                              median = stats::median(x, na.rm = TRUE))}
      return(x)
    })))
    SummarizedExperiment::assays(SE)[[assay]] <- D
  }

  ### remove proteins/peptides with an (almost) constant value (variance near zero)
  v <- matrixStats::rowVars(as.matrix(SummarizedExperiment::assay(SE, assay)))
  ind_zeroVar <- (v < 1e-25)
  SE <- SE[!ind_zeroVar, ]

  if (nrow(SE) == 0) {
    if (verbose) warning("No rows remained. Please increase propNA.")
    return(NULL)
  }



  return(SE)
}



