#' Simple volcano plot from p-value, fold change and significance category
#'
#' @param p **numeric** \cr
#' Vector containing p-values.
#' @param FC **numeric** \cr
#' Vector containing fold changes.
#' @param significanceCategories **factor** \cr
#' The significance categories for the volcano plot, e.g. generated by
#' [.calcSignCat_ttest]
#' @param logBaseFC **numeric(1)** \cr
#' The base for the log-transformation of fold changes. Default is 2.
#' @param logBaseP **numeric(1)** \cr
#' The base for the log-transformation of p values. Default is 10
#' @param thresP **numeric(1)** \cr
#' Threshold for the p-values, used to draw a horizontal line. Default is 0.05.
#' @param thresFC **numeric()** \cr
#' Threshold for the fold changes, used to draw two vertical lines at thresFC and
#' 1/thresFC. Default is 2.
#' @param colour1 **character(1)** \cr
#' The color for not significant proteins. Default is "grey".
#' @param colour2 **character(1)** \cr
#' The color for significant proteins. Defaults is "black".
#' @param colour3 **character(1)** \cr
#' The color for significant proteins after FDR correction. Default is "orange".
#' @param symmetricX **logical(1)** \cr
#' If \code{TRUE}, x-axis limits will be made symmetric (not used if xlim is
#' defined). Default is TRUE.
#' @param legendPosition **character(1)** \cr
#' The positioning of the legend. Options are "none", "left", "right", "bottom",
#' "top" and "inside".
#' @param baseSize **numeric(1)** \cr
#' Base size for the plots. Default is 15.
#' @param xlim **numeric(2)** \cr
#' The limits for x-axis. Default is NULL, i.e. will be determined automatically.
#' @param ylim **numeric(2)** \cr
#' The limits for y-axis. Default is NULL, i.e. will be determined automatically.
#' @param alpha **numeric(1)** \cr
#' The degree of transparency of the data points, between 0 and 1. Default is 1,
#' i.e. no transparency.
#' @param pointSize **numeric(1)** \cr
#' The size of the data points. Default is 3.
#' @param linewidth **numeric(1)** \cr
#' The width of the threshold lines. Default is 2.
#' @param showThresLine **logical(1)** \cr
#' If \code{TRUE}, threshold lines are drawn at \code{thresP} and at
#' \code{thresFC} (and its inverse). Default is TRUE.
#'
#' @return A ggplot object containing the volcano plot.
#' @export
#'
#' @seealso [VolcanoPlot_ttest()], [VolcanoPlot_ANOVA()]
#'
#' @examples
#'

VolcanoPlot <- function(p,
                        FC,
                        significance_category,
                        logBaseFC = 2,
                        logBaseP = 10,
                        thresP = 0.05,
                        thresFC = 2,
                        colour1 = "grey",
                        colour2 = "black",
                        colour3 = "orange",
                        symmetricX = TRUE,
                        legendPosition = "bottom",
                        baseSize = 15,
                        xlim = NULL,
                        ylim = NULL,
                        alpha = 0.5,
                        pointSize = 3,
                        linewidth = 2,
                        showThresLine = TRUE) {


  ### transform p-values and fold changes and thresholds
  transformed_FC <- log(FC, base = logBaseFC) # default: log2(FC)
  transformed_p <- -log(p, base = logBaseP) # default: -log10(p)

  log_thres_fc <- log(thresFC, base = logBaseFC)
  log_thres_p <- -log(thresP, base = logBaseP)


  RES <- data.frame(transformed_FC = transformed_FC,
                    transformed_p = transformed_p,
                    significance = significance_category)


  significance <- RES$significance
  RES <- na.omit(RES) # remove NA values before plotting


  plot <- ggplot2::ggplot(data = RES, ggplot2::aes(x = transformed_FC,
                                                   y = transformed_p,
                                                   colour = significance)) +
    ggplot2::geom_point(alpha = alpha, show.legend = TRUE, size = point_size) +
    ggplot2::scale_colour_manual(values = c("not significant" = colour1,
                                            "significant" = colour2,
                                            "significant after FDR correction" = colour3),
                                 drop = FALSE,
                                 na.translate = FALSE) +

    ggplot2::xlab(paste0("log",logBaseFC,"(FC)")) +
    ggplot2::ylab(paste0("-log",logBaseP,"(p)")) +
    ggplot2::guides(colour = ggplot2::guide_legend(override.aes = list(size = point_size*1.5)))


  if (!is.null(baseSize)) {
    plot <- plot + ggplot2::theme_bw(base_size = baseSize)
  } else {
    plot <- plot + ggplot2::theme_bw()
  }

  plot <- plot + ggplot2::theme(legend.position = legendPosition)

  ### if xlim is not set, use max/min FC and make it symmetric
  if (symmetricX) {
    xlim_tmp <- max(abs(RES$transformed_FC), na.rm = TRUE)
    xlim <- c(-xlim_tmp, xlim_tmp)
  }
  if (!is.null(xlim)) {
    plot <- plot + ggplot2::xlim(xlim)
  }
  if (!is.null(ylim)) {
    plot <- plot + ggplot2::ylim(ylim)
  }

  ## draw threshold lines
  if (showThresLine) {
    plot <- plot + ggplot2::geom_hline(yintercept = log_thres_p, linetype = "dotted", linewidth = linewidth) +
      ggplot2::geom_vline(xintercept =  log_thres_fc, linetype = "dotted", linewidth = linewidth) +
      ggplot2::geom_vline(xintercept = -log_thres_fc, linetype = "dotted", linewidth = linewidth)
  }

  return(plot)

}



################################################################################
################################################################################
################################################################################



#' Volcano plot for a t-test result.
#'
#' @param RES **data.frame** \cr
#' The results from a t-test.
#' @param columnNameP **character(1)** \cr
#' The column name for p-value.
#' @param columnNamePadj **character(1)** \cr
#' The column name for adjusted p-value.
#' @param columnNameFC **character(1)** \cr
#' The column name for fold change.
#' @param thresFC **numeric(1)** \cr
#' The threshold for fold change. Default is 2.
#' @param thresP **numeric(1)** \cr
#' The threshold for p-value. Default is 0.05.
#' @param logBaseFC **numeric(1)** \cr
#' The base for the fold changes log-transformation. Default is 2.
#' @param logBaseP **numeric(1)** \cr
#' The base for the p-values log-transformation. Default is 10.
#' @param isFCLog **logical(1)** \cr
#' If \code{TRUE}, fold change is already log-transformed. Default is FALSE.
#' @param isPLog **logical(1)** \cr
#' If \code{TRUE}, p-value is already log-transformed. Default is FALSE.
#' @param groupName1 **character(1)** \cr
#' The name of the first group. Default is "group1".
#' @param groupName2 **character(1)** \cr
#' The name of the second group. Default is "group2".
#' @param plotHeight **numeric(1)** \cr
#' The height of the plot. Default is 15.
#' @param plotWidth **numeric(1)** \cr
#' The width of the plot. Default is 15.
#' @param plotDPI **integer(1)** \cr
#' The resolution of the plot. Default is 300.
#' @param plotDevice **character(1)** \cr
#' The plot device that is used for the resulting plot. Options are "pdf" and
#' "png". Default is "pdf".
#' @param outputPath **character(1)** \cr
#' The path for the output file. Default is NULL.
#' @param suffix **character(1)** \cr
#' The suffix for the output file. Default is NULL.
#' @param addAnnotation **logical(1)** \cr
#' If \code{TRUE}, annotation will be added. Default is TRUE.
#' @param ... Additional arguments passed on to [VolcanoPlot()], e.g.
#' \code{colour1}, \code{colour2}, \code{colour3}, \code{symmetricX},
#' \code{legendPosition}, \code{baseSize}, \code{alpha}, \code{pointSize},
#' \code{linewidth} or \code{showThresLine}.
#'
#' @return A ggplot object of the volcano plot from a ttest result.
#' @export
#'
#' @seealso [VolcanoPlot()], [VolcanoPlot_ANOVA()], [add_labels()]
#'
#' @examples
#'

VolcanoPlot_ttest <- function(RES,
                        columnNameP = "p",
                        columnNamePadj = "padj",
                        columnNameFC = "FC",

                        thresFC = 2,
                        thresP = 0.05,
                        logBaseFC = 2,
                        logBaseP = 10,
                        isFCLog = FALSE,
                        isPLog = FALSE,

                        groupName1 = "group1",
                        groupName2 = "group2",

                        plotHeight = 15,
                        plotWidth = 15,
                        plotDPI = 300,
                        plotDevice = "pdf",

                        outputPath = NULL,
                        suffix = NULL,
                        addAnnotation = TRUE,
                        ...) {


  # make check work
  #if(getRversion() >= "2.15.1")  utils::globalVariables(c("transformed_FC", "transformed_p", "significance"), add = FALSE)


  p <- RES[,columnNameP]
  padj <- RES[,columnNamePadj]
  FC <- RES[,columnNameFC]

  if (isFCLog) {
    FC <- logBaseFC^FC
  }
  if (isPLog) {
    p <- logBaseP^(-p)
    padj <- logBaseP^(-padj)
  }



  RES$significance <- calculate_significance_categories_ttest(p = p,
                                                              pAdj = padj,
                                                              fc = FC,
                                                              thresFC = thresFC,
                                                              thresP = thresP)


  plot <- VolcanoPlot(p = p,
                      FC = FC,
                      significance_category = RES$significance,
                      thresFC = thresFC,
                      thresP = thresP,
                      ...)

  return(plot = plot) # its not necessary to return the data also, they are already present in the plot object
}



################################################################################
################################################################################
################################################################################



#' Volcano Plots for an ANOVA result.
#'
#' @param RES **data.frame** \cr
#' The results from an ANOVA.
#' @param columnNamePAnova **character(1)** \cr
#' The column name for the p-values.
#' @param columnNamePAnovaAdj **character(1)** \cr
#' The column name for the adjusted p-values.
#' @param columnsFC **integer** \cr
#' The column indices of the fold changes.
#' @param columnsPPosthoc **integer** \cr
#' The column indices for the posthoc p-values.
#' @param symmetricX **logical(1)** \cr
#' If \code{TRUE}, x-axis limits will be made symmetric (not used if xlim is
#' defined). Default is FALSE.
#' @param baseSize **numeric(1)** \cr
#' The base size for the theme. Default is NULL.
#' @param addLabels **logical(1)** \cr
#' If \code{TRUE}, labels will be added. Default is FALSE.
#' @param ... Additional arguments passed on to [VolcanoPlot()], e.g.
#' \code{logBaseFC}, \code{logBaseP}, \code{thresP}, \code{thresFC},
#' \code{colour1}, \code{colour2}, \code{colour3}, \code{legendPosition},
#' \code{xlim}, \code{ylim}, \code{alpha}, \code{pointSize}, \code{linewidth}
#' or \code{showThresLine}.
#'
#' @return A list of ggplots of the volcano plot from an ANOVA result.
#' @export
#'
#' @seealso [VolcanoPlot()], [VolcanoPlot_ttest()], [add_labels()]
#' @examples
VolcanoPlot_ANOVA <- function(RES,
                              columnNamePAnova = "p.anova",
                              columnNamePAnovaAdj = "p.anova.fdr",
                              columnsFC, # spaltennnummer
                              columnsPPosthoc, # spaltennnummer
                              symmetricX = FALSE,
                              baseSize = NULL,
                              addLabels = FALSE,
                              ...) {

  nr_comparisons <- length(columnsPPosthoc)
  if (length(columnsFC) != nr_comparisons) stop("columnsFC and columnsPPosthoc must have the same length!")


  #nr_groups <- length(columnsPPosthoc)
  #if (length(columnsFC) != nr_groups) stop("columnsFC and columnsPPosthoc must have the same length!")

  p_anova <- RES[, columnNamePAnova]
  p_anova_adj <- RES[, columnNamePAnovaAdj]
  p_anova <- RES[, columnNamePAnova]
  p_anova_adj <- RES[, columnNamePAnovaAdj]
  #nr_comparisons <- choose(n = nr_groups, k = 2) # pairwise comparisons between two groups

  # names of the comparisons
  comp_names <- colnames(RES)[columnsFC]
  comp_names <- substring(comp_names, 4) # remove "FC_" at beginning
  comp_names <- stringr::str_replace_all(comp_names, "devided_by_", "vs")

  #comp_names <- stringr::str_replace_all(comp_names, "FC_", "")
  #comp_names <- stringr::str_replace_all(comp_names, "_", " ")

  Volcano_plots <- list()
  for (i in 1:nr_comparisons) {

    p_posthoc <- RES[, columnsPPosthoc[i]]
    fc <- RES[, columnsFC[i]]
    p_posthoc <- RES[, columnsPPosthoc[i]]
    fc <- RES[, columnsFC[i]]

    X <- cbind(p_anova, p_anova_adj, p_posthoc, fc)

    significance <- calculate_significance_categories_ANOVA(p_posthoc = p_posthoc, p_anova_adj = p_anova_adj, p_anova = p_anova, fc = fc, thres_fc = 2, thres_p = 0.05)

    X <- cbind(X, significance)


    plot <- VolcanoPlot(p = p_posthoc,
                        FC = fc,
                        significance_category = significance,
                        symmetricX = symmetricX,
                        baseSize = baseSize,
                        ...)

    plot <- plot + ggplot2::ggtitle(comp_names[i])

    if (addLabels) {
      plot <- add_labels(plot,
                 label_type = "FDR",
                 ind = NULL,
                 protein_name_column = NULL,
                 protein_names = RES$Gene.names)
    }

    Volcano_plots[[i]] <- plot

  }
  return(Volcano_plots)
}




################################################################################
################################################################################
################################################################################


### which to label:
## significant after FDR correction
## significant
## top 10 on each side?




#' Add labels to a volcano plot.
#'
#' @param RES_Volcano **ggplot** \cr
#' The result from [VolcanoPlot()], [VolcanoPlot_ttest()] or
#' [VolcanoPlot_ANOVA()], i.e. a ggplot object containing the transformed data
#' and significance categories.
#' @param label_type **character(1)** \cr
#' The label type. Options are "FDR" (significant after correction), "noFDR"
#' (significant without correction) or "index" (define indices to label via
#' \code{ind}).
#' @param ind **integer** \cr
#' The indices to label if \code{label_type} is "index".
#' @param protein_name_column **character(1)** \cr
#' The column name of the protein names in the \code{RES_Volcano} data.
#' @param protein_names **character** \cr
#' The names of the proteins.
#' @return A ggplot object with labels.
#' @export
#'
#' @seealso [VolcanoPlot()], [VolcanoPlot_ttest()], [VolcanoPlot_ANOVA()]
#'
#' @examples
#'

add_labels <- function(RES_Volcano,
                       label_type = "FDR",
                       ind = NULL,
                       protein_name_column = "Gene.names",
                       protein_names = NULL) {

  if (label_type == "FDR") {
    ind_label <- which(RES_Volcano$data$significance == "significant after FDR correction")
    if (length(ind_label) == 0) {
      warning("No significant proteins after FDR correction for labelling. Try changing label_type to noFDR or lower the fold change threshold.")
      return(RES_Volcano$plot)
    }
  }
  if (label_type == "noFDR") {
    ind_label <- which(RES_Volcano$data$significance %in% c("significant", "significant after FDR correction"))
    if (length(ind_label) == 0) {
      warning("No significant proteins for labelling. Try lowering the fold change threshold.")
      return(RES_Volcano$plot)
    }
  }
  if (label_type == "index") {
    ind_label <- ind
  }

  ind_label_down <- ind_label[RES_Volcano$data$transformed_FC[ind_label] < 0]
  ind_label_up <- ind_label[RES_Volcano$data$transformed_FC[ind_label] > 0]


  labels_up <- rep(NA, nrow(RES_Volcano$data))
  labels_down <- rep(NA, nrow(RES_Volcano$data))
  if (is.null(protein_names)) {
    labels_up[ind_label_up] <- RES_Volcano$data[, protein_name_column][ind_label_up]
    labels_down[ind_label_down] <- RES_Volcano$data[, protein_name_column][ind_label_down]
  } else {
    labels_up[ind_label_up] <- protein_names[ind_label_up]
    labels_down[ind_label_down] <- protein_names[ind_label_down]
  }

  nudge_x = 0.2
  nudge_y = 0.2


  # change axis limits to have more space for labels
  xaxis_limits <- ggplot2::layer_scales(RES_Volcano)$x$get_limits()
  xaxis_limits <- xaxis_limits * 1.1

  yaxis_limits <- ggplot2::layer_scales(RES_Volcano)$y$get_limits()
  yaxis_limits[2] <- yaxis_limits[2] * 1.1 # only change upper limit
  yaxis_limits[2] <- yaxis_limits[2] * 1.1 # only change upper limit

  ### add labels
  plot <- RES_Volcano +
    ggplot2::ylim(yaxis_limits) + ggplot2::xlim(xaxis_limits) +
    ggrepel::geom_label_repel(ggplot2::aes(label = labels_up), size = 2,
                              nudge_x = nudge_x, nudge_y = nudge_y, show.legend = FALSE,
                              max.overlaps = 20) +
    ggrepel::geom_label_repel(ggplot2::aes(label = labels_down), size = 2,
                              nudge_x = -nudge_x, nudge_y = nudge_y, show.legend = FALSE,
                              max.overlaps = 20)

  return(plot)
}



