
#' Boxplots for biomarker candidates including the data point (jitter).
#'
#' @param SE **SummarizedExperiment object** \cr
#' Data in a SummarizedExperiment object, e.g. output SE from [prepareData]
#' function. It should already be filtered for interesting candidates and
#' intensities should be log-transformed.
#' @param assay  **character(1)** \cr
#' The name of the assay in SE containing the protein intensities that should
#' be used for the PCA plot. Default is "intensity_norm", which uses the
#' normalized protein intensities if the SE object was generated by
#' [prepareData].
#' @param groupColumn **character(1)** \cr
#' The name of the column in the colData of SE containing the groups that will
#' be compared by the t-test. Please make sure that exactly two groups are
#' present.
#' @param proteinNameColumn **character(1)** \cr
#' The name of the column in the rowData of SE containing the protein names, e.g.
#' accessions or gene names. Default is \code{"Protein"}. This column will be
#' used to label the boxplots.
#' @param groupColours **character** \cr
#' Vector of colours for the groups. Default is NULL (default ggplot2 colour
#' palette will be used).
#' @param plotDevice **character(1)** \cr
#' Device to use for saving plots. Default is "pdf".
#' @param plotHeight **numeric(1)** \cr
#' Plot height in cm. Default is \code{15}.
#' @param plotWidth **numeric(1)** \cr
#' Plot width in cm. Default is \code{15}.
#' @param plotDPI **integer(1)** \cr
#' Plot resolution in DPI. Default is \code{300}.
#' @param outputPath **character(1)** \cr
#' Path to the output folder. The folder must already exist. If NULL (default),
#' plots are not saved.
#' @param suffix **character(1)** \cr
#' Suffix to add to the output file names. Default is "". Should ideally start
#' with an underscore "_".
#' @param plotNALevel **logical(1)** \cr
#' If \code{TRUE}, data points will be plotted if the group variable is NA.
#' Default is FALSE, so data points with missing group variable will be omitted.
#'
#' @return Nothing, saves pdf or png files with boxplots to the output folder.
#' @export
#'
#' @importFrom checkmate assertCharacter assertChoice assertCount assertDirectoryExists
#' @importFrom checkmate assertFlag assertNumber assertSubset assertTRUE
#' @importFrom ggplot2 aes geom_boxplot geom_jitter ggplot ggtitle labs
#' @importFrom ggplot2 scale_fill_manual theme theme_bw
#' @importFrom grDevices dev.off pdf png
#' @importFrom methods is
#' @importFrom pbapply setpb startpb
#' @importFrom scales hue_pal
#' @importFrom stats na.omit
#' @importFrom SummarizedExperiment assays colData rowData
#'
#' @examples
#'file_proteins <- system.file("extdata", "proteins_HCC.csv", package = "ProtStatsWF")
#'file_clinical  <- system.file("extdata", "clinical_data.csv", package = "ProtStatsWF")
#'
#'D_hcc <- prepareData(dataPath = file_proteins, intensityColumns = 6:43,
#'                     proteinNameColumn = "Protein", sampleInfoPath = file_clinical,
#'                     sampleNameColumn = "Sample", verbose = FALSE)
#'
#'ttest(SE = D_hcc$SE, assay = "intensity_norm",
#'                   groupColumn = "Group", sampleColumn = "PatientID",,
#'                   logBeforeTest = FALSE, delogForFC = TRUE, logBase = 2,
#'                   minObs = 3, paired = TRUE)
#' fc_col <- paste0("FC_", levels(group_hcc)[[1]], "_divided_by_", levels(group_hcc)[[2]])
#' sig_cats   <- .calcSignCat_ttest(
#'  p = ttest_res$p, pAdj = ttest_res$p.fdr, fc = ttest_res[[fc_col]]
#')
#'candidates <- which(as.character(sig_cats) == "significant after FDR correction")
#'
#' Boxplots_candidates(SE = SE[candidates, ],
#' assay = assayName,
#' groupColumn = groupColumn,
#' proteinNameColumn = proteinNameColumn,
#' outputPath = getwd())
BoxplotsCandidates <- function(SE,
                                assay,
                                groupColumn,
                                proteinNameColumn,
                                groupColours = NULL,
                                logData = TRUE,
                                logBase = 2,
                                plotDevice = "pdf",
                                plotHeight = 15,
                                plotWidth = 15,
                                plotDPI = 200,
                                outputPath = NULL,
                                suffix = NULL,
                                plotNALevel = FALSE) {

  checkmate::assertTRUE(methods::is(SE, "SummarizedExperiment"))
  checkmate::assertSubset(assay, names(SummarizedExperiment::assays(SE)))
  checkmate::assertSubset(groupColumn, colnames(SummarizedExperiment::colData(SE)))
  checkmate::assertSubset(proteinNameColumn, colnames(SummarizedExperiment::rowData(SE)))
  nr_groups <- length(unique(SummarizedExperiment::colData(SE)[, groupColumn]))
  checkmate::assertCharacter(groupColours, len = nr_groups, null.ok = TRUE)
  checkmate::assertFlag(logData)
  checkmate::assertNumber(logBase, lower = 1)
  checkmate::assertChoice(plotDevice, c("pdf", "png"))
  checkmate::assertNumber(plotHeight, lower = 0)
  checkmate::assertNumber(plotWidth, lower = 0)
  checkmate::assertCount(plotDPI, positive = TRUE)
  checkmate::assertCharacter(outputPath, len = 1, null.ok = TRUE)
  if (!is.null(outputPath)) checkmate::assertDirectoryExists(outputPath, access = "w")
  checkmate::assertCharacter(suffix, len = 1, null.ok = TRUE)
  checkmate::assertFlag(plotNALevel)

  if (plotDevice == "pdf" & !is.null(outputPath)) {
    grDevices::pdf(paste0(outputPath, "/boxplots_candidates", suffix, ".pdf"),
                   height = plotHeight/2.54,
                   width = plotWidth/2.54)
  }

  D <- as.data.frame(SummarizedExperiment::assays(SE)[[assay]])
  id <- SummarizedExperiment::rowData(SE)
  group <- SummarizedExperiment::colData(D_hcc$SE)[,groupColumn]

  pb <- pbapply::startpb(min = 0, max = nrow(D))
  for (i in seq_along(nrow(D))) {

    # prepare data for single protein
    data <- data.frame(value = unlist(D[i,]), group = group)

    data <- data[!is.na(data$value),]
    if (nrow(data) == 0) {
      warning(paste0("Only missing values for row ", i, " in data set."))
      next
    }
    data$group <- factor(data$group, levels = levels(group))

    value <- NULL # to silence notes while checking package

    plot <- ggplot2::ggplot(data = data,
                            ggplot2::aes(x = group, y = value, fill = group)) +
      ggplot2::geom_boxplot(outlier.shape = NA) +
      ggplot2::geom_jitter() +
      ggplot2::theme_bw() +
      ggplot2::theme(legend.position = "bottom") +
      ggplot2::labs(fill = groupColumn, y = "log2(intensity)", x = groupColumn) +
      ggplot2::ggtitle(id[[proteinNameColumn]][i])

    if (is.null(groupColours)) {
      groupColours <- scales::hue_pal()(length(levels(group)))
    }
    names(groupColours) <- levels(data$group)
    plot <- plot + ggplot2::scale_fill_manual(values = groupColours,
                                  breaks = names(groupColours), drop = FALSE)
    if (plotDevice == "png" & !is.null(outputPath)) {
      protein_names <- gsub("/", "_", id[[proteinNameColumn]][i])
      grDevices::png(paste0(outputPath, "/boxplots_candidates", "_",
                            protein_names, suffix, ".png"),
              height = plotHeight, width = plotWidth, units = "cm", res = 300)
    }
    plot(plot)
    if (plotDevice == "png" & !is.null(outputPath)) grDevices::dev.off()
    pbapply::setpb(pb, i)
  }

  if (plotDevice == "pdf" & !is.null(outputPath)) grDevices::dev.off()

  return(invisible(NULL))
}



