
#' Generates histograms for p-values, adjusted p-values and fold changes.
#'
#' @param RES **data.frame** \cr
#' The results of a t-test analysis, e.g. generated by [ttest()]. Must contain
#' at least three columns: the p-value, the adjusted p-value and the fold change.
#' @param columnP **character(1)** \cr
#' Name of column that contains the p-values.
#' @param columnPadj **character(1)** \cr
#' Name of column that contains the adjusted p-values.
#' @param columnFC **character(1)** \cr
#' Name of column that contains the fold changes.
#' @param baseSize **numeric(1)** \cr
#' Base size for the plots. Default is 15.
#'
#' @return A list of 3 ggplot objects with a histogram for p-values,
#' adjusted p-values and fold changes each.
#' @export
#'
#' @importFrom checkmate assertCharacter assertDataFrame assertNumber assertSubset
#' @importFrom ggplot2 aes geom_histogram ggplot labs theme_bw xlim
#' @importFrom stats na.omit
#'
#' @examples
#'file_proteins <- system.file("extdata", "proteins_HCC.csv", package = "ProtStatsWF")
#'file_clinical  <- system.file("extdata", "clinical_data.csv", package = "ProtStatsWF")
#'
#'D_hcc <- prepareData(dataPath = file_proteins, intensityColumns = 6:43,
#'                     proteinNameColumn = "Protein", sampleInfoPath = file_clinical,
#'                     sampleNameColumn = "Sample", verbose = FALSE)
#'
#'RES <- ttest(SE = D_hcc$SE, assay = "intensity_norm",
#'                   groupColumn = "Group", sampleColumn = "PatientID",,
#'                   logBeforeTest = FALSE, delogForFC = TRUE, logBase = 2,
#'                   minObs = 3, paired = TRUE)
#'
#' pvalueFCHistogram(RES, columnNameP = "p", columnNamePadj = "padj",
#' columnNameFC = "FC")
pvalueFCHistogram <- function(RES,
                             columnP = "p",
                             columnPadj = "padj",
                             columnFC = "FC",
                             baseSize = 15) {

  checkmate::assertDataFrame(RES, min.rows = 1)
  checkmate::assertCharacter(columnP, len = 1)
  checkmate::assertSubset(columnP, colnames(RES))
  checkmate::assertCharacter(columnPadj, len = 1)
  checkmate::assertSubset(columnPadj, colnames(RES))
  checkmate::assertCharacter(columnFC, len = 1)
  checkmate::assertSubset(columnFC, colnames(RES))
  checkmate::assertNumber(baseSize, lower = 0)

  D <- data.frame(p = RES[[columnP]],
                  padj = RES[[columnPadj]],
                  FC = RES[[columnFC]])

  D <- stats::na.omit(D) # remove NAs before plotting

  p <- padj <- FC <- NULL # silence notes when checking the package

  pl_hist_p <- ggplot2::ggplot(D, ggplot2::aes(x = p)) +
    ggplot2::geom_histogram(breaks = seq(0,1, 0.05)) +
    ggplot2::theme_bw(base_size = baseSize) +
    ggplot2::labs(title = "Histogram of p-values",
         x = "p-value",
         y = "Frequency") +
    ggplot2::xlim(0,1)

  pl_hist_padj <- ggplot2::ggplot(D, ggplot2::aes(x = padj)) +
    ggplot2::geom_histogram(breaks = seq(0,1, 0.05)) +
    ggplot2::theme_bw(base_size = baseSize) +
    ggplot2::labs(title = "Histogram of adjusted p-values",
         x = "Adjusted p-value",
         y = "Frequency") +
    ggplot2::xlim(0,1)

  pl_hist_FC <- ggplot2::ggplot(D, ggplot2::aes(x = log2(FC))) +
    ggplot2::geom_histogram(binwidth = 0.25) +
    ggplot2::theme_bw(base_size = baseSize) +
    ggplot2::labs(title = "Histogram of fold changes",
         x = "log2 Fold change",
         y = "Frequency")

  return(list("histogram_p_value" = pl_hist_p,
              "histogram_adjusted_p_value" = pl_hist_padj,
              "histogram_fold_change" = pl_hist_FC))
}


