#' PCA plot for proteomics data.
#'
#' @param SE  **SummarizedExperiment object** \cr
#' Data in a SummarizedExperiment object, e.g. output SE from [prepareData]
#' function.
#' @param assay  **character(1)** \cr
#' The name of the assay in SE containing the protein intensities that should
#' be used for the PCA plot. Default is "intensity_norm", which uses the
#' normalized protein intensities if the SE object was generated by
#' [prepareData].
#' @param groupForColour  **character(1)** \cr
#' The name of the column in the colData of SE to be used for colouring the
#' points in the PCA plot. Default is NULL, so no colouring.
#' @param colourType **character(1)** \cr
#' Colour type, either "discrete" (default, discrete set of colours) or
#' "continuous" (colourbar).
#' @param groupForShape  **character(1)** \cr
#' The name of the column in the colData of SE to be used for shaping the points
#'  in the PCA plot.
#' @inheritParams .prepDataForPCA imputeMethod propNA
#' @param scale **logical(1)** \cr
#' Whether to scale data before calculating the PCA. Default is TRUE.
#' @param PCx **integer(1)** \cr
#' The principal component to be plotted on the x-axis. Default is 1.
#' @param PCy **integer(1)** \cr
#' The principal component to be plotted on the y-axis. Default is 2.
#' @param groupColours **character** \cr
#' Vector of colours for the groups. Default is NULL (default ggplot2 colour
#' palette will be used).
#' @param groupShapes **integer** \cr
#' Vector of shapes (pch values) for the groups defined by `groupForShape`.
#' Default is NULL (shapes 1, 2, 3, ... are used). Please see
#' [graphics::pch()] for further information.
#' @param NAValueColour **character(1)** \cr
#' Colour for data points with missing values in the groupForColour variable.
#' Default is "grey".
#' @param NAValueShape **integer(1)** \cr
#' Shape for data points with missing values in the groupForShape variable.
#' Default is 0 (hollow square). Please see [graphics::pch()] for further
#' information.
#' @param alpha **numeric(1)** \cr
#' Transparency factor for data points. Default is 1, no transparency.
#' @param label **logical(1)** \cr
#' Whether to label the points with the sample names. Default is FALSE.
#' @param labelSeed **numeric(1)** \cr
#' Seed for random number generator used for label placement. Default is NA
#' (no seed), which may lead to different label placement for multiple
#' executions of this function.
#' @param labelSize **numeric(1)** \cr
#' Size of the labels. Default is 4.
#' @param pointSize **numeric(1)** \cr
#' Size of data points in the PCA. Default is 4.
#' @param baseSize **numeric(1)** \cr
#' Base size for the plot. Default is 15.
#' @param xlim **numeric(2)** \cr
#' Limits for the x-axis. Default is NULL (automatic).
#' @param ylim **numeric(2)** \cr
#' Limits for the y-axis. Default is NULL (automatic).
#' @param verbose **logical(1)** \cr
#' If TRUE (default), messages are printed out.
#'
#' @return
#' @export
#'
#' @importFrom checkmate assertCharacter assertFlag assertIntegerish assertNumeric
#' @importFrom checkmate assertSubset assertTRUE
#' @importFrom ggplot2 aes geom_point ggplot guide_legend guides labs
#' @importFrom ggplot2 scale_colour_continuous scale_colour_discrete scale_colour_manual
#' @importFrom ggplot2 scale_shape_manual theme_bw xlim xlab ylim ylab
#' @importFrom ggrepel geom_text_repel
#' @importFrom methods is
#' @importFrom scales hue_pal
#' @importFrom stats predict prcomp
#' @importFrom SummarizedExperiment assays colData rowData
#'
#' @examples
PCA_Plot <- function(SE,
                     assay = "intensity_norm",
                     groupForColour = NULL,
                     colourType = "discrete",
                     groupForShape = NULL,
                     imputeMethod = "mean",
                     propNA = 0,
                     scale = TRUE,
                     PCx = 1,
                     PCy = 2,
                     groupColours = NULL,
                     groupShapes = NULL,
                     NAValueColour = "grey",
                     NAValueShape = 0,
                     alpha = 1,
                     label = FALSE,
                     labelSeed = NA,
                     labelSize = 4,
                     pointSize = 4,
                     baseSize = 11,
                     xlim = NULL,
                     ylim = NULL,
                     verbose = TRUE
) {
  checkmate::assertTRUE(methods::is(SE, "SummarizedExperiment"))
  checkmate::assertSubset(groupForColour,
                          colnames(SummarizedExperiment::colData(SE)))
  checkmate::assertSubset(colourType, c("discrete", "continuous"))
  checkmate::assertSubset(groupForShape,
                          colnames(SummarizedExperiment::colData(SE)))
  checkmate::assertFlag(scale)
  checkmate::assertIntegerish(c(PCx, PCy), lower = 1, any.missing = FALSE,
                              unique = TRUE)
  nr_groups <- length(unique(SummarizedExperiment::colData(SE)[, groupForColour]))
  checkmate::assertCharacter(groupColours, len = nr_groups, null.ok = TRUE)
  nr_shape_groups <- if (!is.null(groupForShape)) length(unique(SummarizedExperiment::colData(SE)[, groupForShape])) else NULL
  checkmate::assertIntegerish(groupShapes, len = nr_shape_groups, lower = 0,
                              upper = 255, null.ok = TRUE)
  checkmate::assertCharacter(NAValueColour, len = 1, null.ok = TRUE)
  checkmate::assertIntegerish(NAValueShape, len = 1, lower = 0, upper = 255)
  checkmate::assertNumeric(alpha, lower = 0, upper = 1)
  checkmate::assertFlag(label)
  checkmate::assertIntegerish(labelSeed, len = 1, lower = 0)
  checkmate::assertIntegerish(labelSize, len = 1, lower = 0)
  checkmate::assertIntegerish(pointSize, len = 1, lower = 0)
  checkmate::assertIntegerish(baseSize, len = 1, lower = 0)
  checkmate::assertNumeric(xlim, len = 2, sorted = TRUE, null.ok = TRUE)
  checkmate::assertNumeric(ylim, len = 2, sorted = TRUE, null.ok = TRUE)
  checkmate::assertFlag(verbose)

  filteredSE <- .prepDataForPCA(SE = SE, assay = assay,
    imputeMethod = imputeMethod, propNA = propNA,verbose = verbose)
  if (is.null(filteredSE)) {
    if (verbose) message("All rows were filtered out. Please increase propNA.")
    return(list("plot" = NULL, "D_PCA_plot" = NULL, "pca" = NULL))
  }
  D <- SummarizedExperiment::assays(filteredSE)[[assay]]
  if (verbose) message(nrow(D), " of ", nrow(SE), " rows are used for PCA.")
  id <- SummarizedExperiment::rowData(filteredSE)
  group1 <- group2 <- NULL
  if (!is.null(groupForColour)) {
    group1 <- SummarizedExperiment::colData(filteredSE)[,groupForColour]
    if (colourType == "discrete") group1 <- factor(group1)
  }
  if (!is.null(groupForShape)) {
    group2 <- SummarizedExperiment::colData(filteredSE)[,groupForShape]
    group2 <- factor(group2)
  }

  if (is.null(groupColours) && !is.null(groupForColour) && colourType == "discrete") {
    groupColours <- scales::hue_pal()(nr_groups)
  }

  pca <- stats::prcomp(t(D), scale. = scale)
  pred <- stats::predict(pca, t(D))
  summ <- summary(pca)
  var50 <- which(summ$importance[3,] >= 0.5)[1]
  if (verbose)
    message("50% explained variance reached with ", var50, " principle components.")
  D_PCA <- data.frame(pred[, c(PCx, PCy)], label = colnames(D))
  colnames(D_PCA)[1:2] <- c("PCx", "PCy")
  D_PCA <- cbind(D_PCA, SummarizedExperiment::colData(filteredSE))
  if (!is.null(groupForColour)) D_PCA[[groupForColour]] <- group1
  if (!is.null(groupForShape))  D_PCA[[groupForShape]] <- group2
  pl <- ggplot2::ggplot(mapping = ggplot2::aes(x = PCx, y = PCy))
  pl <- pl + ggplot2::geom_point(data = D_PCA, mapping = ggplot2::aes(
      colour = if (!is.null(groupForColour)) .data[[groupForColour]] else NULL,
      shape  = if (!is.null(groupForShape)) .data[[groupForShape]] else NULL),
      size = pointSize, alpha = alpha)
  pl <- pl + ggplot2::labs(colour = groupForColour, shape  = groupForShape)
  if (!is.null(groupForColour)) {
    if (colourType == "discrete") {
      pl <- pl + ggplot2::scale_colour_manual(values = groupColours, na.value = NAValueColour)
    } else {
      pl <- pl + ggplot2::scale_colour_continuous(na.value = NAValueColour)
    }
  }

  if (label) {
    pl <- pl + ggrepel::geom_text_repel(data = D_PCA, ggplot2::aes(x = PCx,
          y = PCy, label = label, colour = group1),
        size = labelSize, seed = labelSeed) +
      ggplot2::guides(colour =
            ggplot2::guide_legend(override.aes = ggplot2::aes(label = "")))
  }

  #### add % of explainable variance to the axis label ####
  pl <- pl + ggplot2::theme_bw(base_size = baseSize) +
    ggplot2::xlab(paste0("PC", PCx, " (", round(100*summ$importance[2,PCx], 1), "%)")) +
    ggplot2::ylab(paste0("PC", PCy, " (", round(100*summ$importance[2,PCy], 1), "%)"))

  ### allow more than 6 different shapes
  shape_values <- if (!is.null(groupShapes)) groupShapes else seq_len(nlevels(group2))
  pl <- pl + ggplot2::scale_shape_manual(values = shape_values,
                                         na.value = NAValueShape)
  if (!is.null(xlim)) pl <- pl + ggplot2::xlim(xlim)
  if (!is.null(ylim)) pl <- pl + ggplot2::ylim(ylim)
  Loadings <- cbind(id, as.data.frame(pca$rotation))
  return(list("D_PCA_plot" = cbind(D_PCA, "Sample" = colnames(D)), "pca" = pca,
              "filteredSE" = filteredSE, "loadings" = Loadings, "plot" = pl))
}

